name: Hourly Chart Screenshot Cron

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  take_screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Snapshot XAUEGP
        run: |
          curl "https://chart6532.vercel.app/api/cron?key=7737655407&symbol=XAUEGP"
          sleep 5
      - name: Snapshot XAUUSD
        run: |
          curl "https://chart6532.vercel.app/api/cron?key=7737655407&symbol=XAUUSD"
          sleep 5
      - name: Snapshot USDEGP
        run: |
          curl "https://chart6532.vercel.app/api/cron?key=7737655407&symbol=USDEGP"
